// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDirectory() {
  return window['go']['utilities']['DirectorySelector']['GetDirectory']();
}

export function SelectDirectory() {
  return window['go']['utilities']['DirectorySelector']['SelectDirectory']();
}
