// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCtx() {
  return window['go']['app']['App']['GetCtx']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function OnDomReady(arg1) {
  return window['go']['app']['App']['OnDomReady'](arg1);
}
