// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetCtx():Promise<context.Context>;

export function GetSelectedProjectPath():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OnDomReady(arg1:context.Context):Promise<void>;

export function SetSelectedProjectPath(arg1:string):Promise<void>;
