// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDestinationDirectory():Promise<string>;

export function GetSourceDirectory():Promise<string>;

export function SelectDirectory(arg1:boolean):Promise<string>;
