// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDestinationDirectory() {
  return window['go']['app']['DirectorySelector']['GetDestinationDirectory']();
}

export function GetSourceDirectory() {
  return window['go']['app']['DirectorySelector']['GetSourceDirectory']();
}

export function SelectDirectory(arg1) {
  return window['go']['app']['DirectorySelector']['SelectDirectory'](arg1);
}
