// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFile() {
  return window['go']['app']['FileSelector']['GetFile']();
}

export function SelectFile() {
  return window['go']['app']['FileSelector']['SelectFile']();
}
