// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {maps} from '../models';

export function CopyFiles(arg1:Array<app.Day>):Promise<void>;

export function CreateProject(arg1:app.Project):Promise<Array<any>>;

export function CreateThumbnail(arg1:string,arg2:app.ProcessedFile):Promise<string>;

export function FindTimezone(arg1:string):Promise<maps.TimezoneResult>;

export function IsVideo(arg1:string):Promise<boolean>;
