// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyFiles(arg1) {
  return window['go']['app']['Processor']['CopyFiles'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['app']['Processor']['CreateProject'](arg1);
}

export function CreateThumbnail(arg1, arg2) {
  return window['go']['app']['Processor']['CreateThumbnail'](arg1, arg2);
}

export function FindTimezone(arg1) {
  return window['go']['app']['Processor']['FindTimezone'](arg1);
}

export function IsVideo(arg1) {
  return window['go']['app']['Processor']['IsVideo'](arg1);
}
